### ISSUE TITLE
Running a Trials in a nested Junit5 test class

### ISSUE THREAD

**Issue by rpolton** [sageserpent-open/americium#44]
When Trials is initialised inside a junit5 nested test class, the junit5-integration annotations can't find the class-local Trials because they can't be static

**Comment by sageserpent-open** [comment]
@rpolton - checking here, is this simply due to not using the correct lifecycle, as described here: https://github.com/sageserpent-open/americium/blob/905a5dde719096d0446f2f98e6ac66fba15de6f6/README.markdown?plain=1#L903 ?

I'm unsure as to whether this is simply an instance versus static field issue engendered by the use of a nested class, or down to some other aspect, possibly reflection looking on the wrong place.

Would you add a minimal reproduction to this ticket, please?

**Comment by rpolton** [comment]
I can confirm that this is due to the @TestInstance annotation being missing from the @Nested test class. Not an issue, therefore 👍

**Comment by sageserpent-open** [comment]
Thanks for checking @rpolton - dodged a bullet there. 😄
